import { atrPct } from "../market/indicators.js";
import { AdaptiveSizingEngine } from "./adaptiveSizingEngine.js";
export class RiskEngine {
  constructor(){this.adaptiveSizing=new AdaptiveSizingEngine();}
  buildTrade({state,symbol,candles,decision}){const settings=state.settings,account=state.account,price=candles.at(-1).close,atr=atrPct(candles),timeframe=settings.scannerTimeframe||"5m";const baseLev=this.decideLeverage({atr,decision,timeframe});let leverage=Math.min(settings.maxLeverage,this.adaptiveSizing.leverageCap(decision,baseLev));if(String(decision.newsRisk||"").match(/Risk\s+([7-9][0-9]|100)/))leverage=Math.max(1,Math.floor(leverage*.5));const stopPct=Math.max(atr*.75*this.timeframeStopMultiplier(timeframe),.22*this.timeframeStopMultiplier(timeframe));const takePct=stopPct*this.rewardMultiplier(timeframe,decision);const riskDollars=account.equity*(settings.baseRisk/100)*this.adaptiveSizing.multiplier(decision);const rawPosition=riskDollars/(stopPct/100||.01);const maxPosition=account.equity*(settings.maxAllocation/100)*leverage;const positionValue=Math.min(rawPosition,maxPosition),margin=positionValue/leverage;const side=decision.action;const stopLoss=side==="LONG"?price*(1-stopPct/100):price*(1+stopPct/100);const takeProfit=side==="LONG"?price*(1+takePct/100):price*(1-takePct/100);return{id:"AX-"+Date.now()+"-"+symbol,symbol,side,status:"OPEN",entry:price,current:price,stopLoss,takeProfit,leverage,positionValue,margin,pnl:0,maxProfit:0,maxDrawdown:0,protected:false,riskDollars,allocationPct:account.equity?(positionValue/account.equity)*100:0,timeframe,expectedHold:this.expectedHold(timeframe),selectedStyle:decision.selectedStyle || "Fixed",openedAt:Date.now(),reason:decision.reason,thesis:decision.thesis||"No thesis",grade:decision.grade||"C",gradeScore:decision.gradeScore||0,edge:decision.edge,probability:decision.probability||decision.edge,uncertainty:decision.uncertainty||50,expectedRR:decision.expectedRR||1.5,regime:decision.regime||"Unknown",pattern:decision.pattern||"Unknown",dna:decision.dna||"Unknown",psychology:decision.psychology||"Unknown",liquidity:decision.liquidity||"Unknown",newsRisk:decision.newsRisk||"No news risk",feeRate:Number(settings.feeRate||0.04)/100,estimatedEntryFee:positionValue*(Number(settings.feeRate||0.04)/100)};}
  decideLeverage({atr,decision,timeframe}){let base=atr>1.2?3:atr>.7?5:atr>.35?8:12;if(["1h","2h","4h","1d","3d"].includes(timeframe))base=Math.min(base,timeframe==="1h"?8:timeframe==="2h"?6:timeframe==="4h"?5:3);if((decision.probability||0)>82&&(decision.uncertainty||100)<35)base+=2;return Math.max(1,base);}
  expectedHold(tf){return({"1m":"3-15 min","3m":"9-30 min","5m":"15-60 min","15m":"45m-3h","1h":"2h-12h","2h":"4h-24h","4h":"8h-3d","1d":"1d-2w","3d":"3d-1mo"})[tf]||"variable";}
  timeframeStopMultiplier(tf){return({"1m":.65,"3m":.8,"5m":1,"15m":1.35,"1h":2,"2h":2.6,"4h":3.4,"1d":5,"3d":7})[tf]||1;}
  rewardMultiplier(tf,decision){const b=({"1m":1.25,"3m":1.35,"5m":1.55,"15m":1.8,"1h":2.2,"2h":2.6,"4h":3,"1d":3.5,"3d":4})[tf]||1.55;return decision.grade==="S"?b*1.25:decision.grade==="A"?b*1.12:b;}
}
